//! Boot-time dispatcher-completeness check — build-time source scanner.
//!
//! CERBER capability added per `docs/SECURITY_AUDIT_2026-07-25_FULL_WORKSPACE.md`
//! §5.1 (finding C7 / M11). See `crates/rope-security/src/dispatcher_completeness.rs`
//! for the full rationale; this file is the mechanical half of that
//! capability — it is what keeps the *input* to the completeness check
//! honest.
//!
//! Every `cargo build` of `rope-node`, this script:
//!
//! 1. Reads `src/rpc_server.rs` as plain text (never compiles/parses full
//!    Rust syntax — that would require pulling in `syn`/`proc-macro2` as a
//!    build-dependency for a job a couple of regexes can do reliably given
//!    the very regular shape of this codebase's match arms).
//! 2. Locates the outer JSON-RPC dispatch match — the block that starts at
//!    `let result = match method {` and reads its **balanced** closing
//!    brace by tracking `{`/`}` depth, so nested `match` expressions
//!    inside individual arm bodies (e.g. the `interaction_type` match
//!    inside the `rope_appendToLedger` arm, or the governance-action match
//!    inside `rope_suspendNode`/`rope_isolateNode`/`rope_eraseNode`) are
//!    included in the scanned text without over-running past the outer
//!    match's own end.
//! 3. Within that block, finds every run of `"lit1" | "lit2" | ... =>` (an
//!    actual match-arm pattern, however many lines it spans) and extracts
//!    the quoted literals inside each run.
//! 4. Keeps only literals that look like a JSON-RPC method name under one
//!    of this node's known namespaces (`rope_`, `eth_`, `net_`, `web3_`,
//!    `anvil_`, `evm_`, or exactly `rpc_methods`/`rpc_modules`). This
//!    filter is what excludes false positives like the `interaction_type`
//!    enum-variant literals (`"Transfer"`, `"BridgeOperation"`, ...) that
//!    also appear as `"lit" => ...` inside the same block but are matches
//!    against a *different* variable, not `method`.
//! 5. Emits the deduplicated, sorted result to
//!    `$OUT_DIR/dispatcher_methods_generated.rs` as a
//!    `pub const ALL_REGISTERED_METHODS: &[&str]`, `include!`'d by
//!    `rpc_auth.rs`.
//!
//! If step 2 cannot find the expected anchor text at all (e.g. a refactor
//! renamed the dispatch variable), the build **fails** rather than
//! silently emitting an empty/stale list — an empty
//! `ALL_REGISTERED_METHODS` would make the runtime completeness check
//! trivially pass and provide zero protection, which is worse than a
//! loud build break.

use std::env;
use std::fs;
use std::path::Path;

use regex::Regex;

const DISPATCH_ANCHOR: &str = "let result = match method {";

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let rpc_server_path = Path::new(&manifest_dir).join("src/rpc_server.rs");
    println!("cargo:rerun-if-changed={}", rpc_server_path.display());

    let source = fs::read_to_string(&rpc_server_path).unwrap_or_else(|e| {
        panic!(
            "dispatcher-completeness build.rs: failed to read {}: {e}",
            rpc_server_path.display()
        )
    });

    let block = extract_dispatch_block(&source).unwrap_or_else(|| {
        panic!(
            "dispatcher-completeness build.rs: could not find the anchor `{DISPATCH_ANCHOR}` \
             (or its balanced closing brace) in {}. This scanner backs the boot-time \
             dispatcher-completeness check (CERBER, SECURITY_AUDIT_2026-07-25_FULL_WORKSPACE.md \
             §5.1) — if the dispatch match was intentionally renamed/restructured, update the \
             `DISPATCH_ANCHOR` constant in build.rs to match, and re-verify the extracted method \
             list against rpc_auth.rs's classification buckets before shipping.",
            rpc_server_path.display()
        )
    });

    let methods = extract_method_literals(&block);
    if methods.is_empty() {
        panic!(
            "dispatcher-completeness build.rs: extracted zero method literals from the dispatch \
             block in {} — this would make the runtime completeness check vacuously pass \
             (protecting nothing). Treat as a build failure, not a warning.",
            rpc_server_path.display()
        );
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("dispatcher_methods_generated.rs");
    let mut body = String::new();
    body.push_str("// @generated by build.rs — do not edit by hand.\n");
    body.push_str(
        "// Mechanically extracted from rpc_server.rs's own dispatch match on every build; \
         see build.rs module docs.\n",
    );
    body.push_str(&format!(
        "pub const ALL_REGISTERED_METHODS: &[&str] = &[\n{}\n];\n",
        methods
            .iter()
            .map(|m| format!("    \"{m}\","))
            .collect::<Vec<_>>()
            .join("\n")
    ));
    fs::write(&dest_path, body).unwrap_or_else(|e| {
        panic!(
            "dispatcher-completeness build.rs: failed to write {}: {e}",
            dest_path.display()
        )
    });
}

/// Return the text of the outer `match method { ... }` block (the braces'
/// contents only, not including `match method {` itself or the final
/// `}`), found by balanced-brace scanning starting right after
/// [`DISPATCH_ANCHOR`].
fn extract_dispatch_block(source: &str) -> Option<&str> {
    let start = source.find(DISPATCH_ANCHOR)?;
    let body_start = start + DISPATCH_ANCHOR.len();
    let bytes = source.as_bytes();
    let mut depth: i32 = 1; // we are already inside the opening `{` of the anchor
    let mut i = body_start;
    while i < bytes.len() {
        match bytes[i] {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(&source[body_start..i]);
                }
            }
            _ => {}
        }
        i += 1;
    }
    None
}

/// Extract every method-name-shaped string literal from match-arm
/// patterns (`"lit1" | "lit2" | ... =>`) within `block`, filtered to
/// known JSON-RPC namespaces. See module docs for the full rationale.
fn extract_method_literals(block: &str) -> Vec<String> {
    // Matches a run of zero-or-more `"literal" |` followed by a final
    // `"literal" =>`. `\s` already spans newlines in the `regex` crate,
    // so multi-line arm patterns (very common in this file) are matched
    // in one pass without a dotall flag.
    let arm_pattern = Regex::new(r#"(?:"[a-zA-Z][a-zA-Z0-9_]*"\s*\|\s*)*"[a-zA-Z][a-zA-Z0-9_]*"\s*=>"#)
        .expect("arm_pattern regex is a compile-time constant");
    let literal_pattern =
        Regex::new(r#""([a-zA-Z][a-zA-Z0-9_]*)""#).expect("literal_pattern regex is a compile-time constant");
    let namespace_pattern = Regex::new(r"^(rope|eth|net|web3|anvil|evm)_[A-Za-z0-9_]+$")
        .expect("namespace_pattern regex is a compile-time constant");

    let mut methods: Vec<String> = Vec::new();
    for arm_match in arm_pattern.find_iter(block) {
        for cap in literal_pattern.captures_iter(arm_match.as_str()) {
            let lit = &cap[1];
            if namespace_pattern.is_match(lit) || lit == "rpc_methods" || lit == "rpc_modules" {
                if !methods.iter().any(|m| m == lit) {
                    methods.push(lit.to_string());
                }
            }
        }
    }
    methods.sort();
    methods
}
